### ISSUE TITLE
TierIV calibration tools

### ISSUE THREAD

**Issue by knzo25** [Deephome/Awesome-LiDAR-Camera-Calibration#2]
(Disclaimer: I am one of the developers)

In TierIV we are developing calibration tools for autonomous driving and as part of those we developed a target-based camera-lidar method and a UI-based manual calibration tool. Although they do not introduce much novelty, they provide quite good results and as we keep developing new calibration tools for different use-cases, we plan to support the repository for a long period of time.

I came to see this curated list of methods, tools, and papers while doing my literature review so I would love it if our software could be included here !

[Link](https://github.com/tier4/CalibrationTools)

Best regards,

Kenzo

**Comment by Deephome** [comment]
Ok, just add it!
