### ISSUE TITLE
The source code for the SOIC could not be found

### ISSUE THREAD

**Issue by Mrcheerui** [Deephome/Awesome-LiDAR-Camera-Calibration#3]
[SOIC: Semantic Online Initialization and Calibration for LiDAR and Camera, 2020](https://arxiv.org/pdf/2003.04260) Its source code address is down

**Comment by Mrcheerui** [comment]
How can I get the source code？I need it.

**Comment by DreamWaterFound** [comment]
More than 2 years have pasted. That looks like fake open source research.
