### ISSUE TITLE
new targetless calibration paper

### ISSUE THREAD

**Issue by qserdel** [Deephome/Awesome-LiDAR-Camera-Calibration#5]
Hello and thanks for your work which has been very helpful to me for choosing a calibration method.

I recently encountered and tested this method presented at the 2023 ICRA conference which shows great results for targetless calibration : https://github.com/koide3/direct_visual_lidar_calibration and associated paper: https://arxiv.org/abs/2302.05094 
Maybe you could add it to your list (Please note that this isn't my work) .

With best regards.

**Comment by Deephome** [comment]
Sure, thanks for your introduction!
